# Generated by Django 3.2.4 on 2021-07-09 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flower', '0002_auto_20210709_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flower',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
