# Generated by Django 3.2.4 on 2021-07-09 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flower', '0003_alter_flower_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flower',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
