# Generated by Django 3.2.4 on 2021-07-13 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flower', '0005_rename_return_date_flower_time'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DateWithTime',
        ),
    ]
