# Generated by Django 3.2.4 on 2021-07-15 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flower', '0010_auto_20210715_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='phone_no',
            field=models.IntegerField(default=960, help_text='Contact phone number'),
        ),
    ]
