# Generated by Django 3.2.4 on 2021-07-15 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flower', '0011_order_phone_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
    ]
