# Generated by Django 3.2.4 on 2021-07-15 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flower', '0012_remove_order_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='phone_no',
            field=models.IntegerField(default='+960', help_text='Contact phone number'),
        ),
    ]
