# Generated by Django 3.2.4 on 2021-07-15 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flower', '0014_alter_order_phone_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product',
        ),
        migrations.AddField(
            model_name='product',
            name='product_id',
            field=models.IntegerField(blank=True, max_length=8, null=True),
        ),
    ]
