# Generated by Django 3.2.4 on 2021-07-15 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flower', '0015_auto_20210715_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_id',
            field=models.IntegerField(blank=True, max_length=4, null=True),
        ),
    ]
